services:

  nginx:
    image: nginx:stable
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './src:/usr/share/nginx/html'
    ports:
      - '8080:80'
    depends_on: 
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - './src:/usr/share/nginx/html'
    depends_on: 
      - db


  db:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - "55432:5432"


volumes:
  db_data:
  pgadmin_data:

